language: cpp
env:
  global:
    - INSTALL_PREFIX=/usr/local
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release
compiler:
  - gcc
  - clang
before_install:
 # install a newer cmake since at this time Travis only has version 2.8.7
 - echo "yes" | sudo add-apt-repository ppa:kalakris/cmake
 - sudo apt-get update -qq
install:
 - sudo apt-get install -qq cmake python-dev python-numpy swig
script:
 - mkdir build
 - cd build
 - cmake ../ -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${BUILD_TYPE}
 - make
 - sudo make install
 - export LD_LIBRARY_PATH=${INSTALL_PREFIX}/lib:${LD_LIBRARY_PATH}
 - export PATH=${INSTALL_PREFIX}/bin:${PATH}
 - SoapySDRUtil --info
 - SoapySDRUtil --make="driver=null"

