########################################################################
## Travis CI config for SoapySDR
##
## * matrix tests compilers and build types
## * python bindings built and installed
## * python3 bindings built and installed
## * minimal testing for command line util
## * minimal testing for python bindings
########################################################################

sudo: required
dist: trusty

language: cpp
compiler: gcc

env:
  global:
    - INSTALL_PREFIX=/usr/local
  matrix:
    - BUILD_TYPE=Debug
    - BUILD_TYPE=Release

before_install:
  # regular ubuntu packages
  - sudo add-apt-repository main
  - sudo add-apt-repository universe

  # update after package changes
  - sudo apt-get update

install:

  # install python support dependencies
  - sudo apt-get install -qq python python-dev python-numpy swig

  # install python3 support dependencies
  - sudo apt-get install -qq python3 python3-dev python3-numpy swig

script:
  - mkdir build
  - cd build
  - cmake ../ -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DPYTHON_EXECUTABLE=/usr/bin/python
  - make
  - sudo make install

  # setup environment paths
  - export LD_LIBRARY_PATH=${INSTALL_PREFIX}/lib:${LD_LIBRARY_PATH}
  - export PATH=${INSTALL_PREFIX}/bin:${PATH}
  - export PYTHONPATH=/usr/lib/python2.7/dist-packages:${PYTHONPATH}
  - export PYTHONPATH=${INSTALL_PREFIX}/lib/python2.7/dist-packages:${PYTHONPATH}

  # basic test for command line utility
  - SoapySDRUtil --info
  - SoapySDRUtil --check=null
  - SoapySDRUtil --make="driver=null"

  # basic test for python bindings
  - python -c "import SoapySDR; print(SoapySDR.getAPIVersion())"
  - python -c "from SoapySDR import *; print SOAPY_SDR_ABI_VERSION"
  - python -c "from SoapySDR import *; print SOAPY_SDR_TIMEOUT"
  - python -c "import SoapySDR; print(SoapySDR.errToStr(SoapySDR.SOAPY_SDR_TIMEOUT))"
  - python -c "import SoapySDR; print(SoapySDR.Device.make('driver=null'))"

  # run unit tests
  - make test

