########################################################################
## AppVeyor config for SoapySDR
########################################################################

version: '{build}'

platform: x64

configuration:
  - Debug
  - Release

environment:
  global:
    INSTALL_PREFIX: C:/Program Files/SoapySDR

# Operating system (build VM template)
os: Windows Server 2012 R2

# branches to build
branches:
  # whitelist
  only:
    - master

# configure and build
build_script:
  - mkdir build
  - cd build
  - cmake ../ -G "Visual Studio 12 Win64" -DGPLOK=FALSE -DCMAKE_INSTALL_PREFIX=%INSTALL_PREFIX% -DCMAKE_BUILD_TYPE=%CONFIGURATION%
  - cmake --build . --config %CONFIGURATION%
  - cmake --build . --config %CONFIGURATION% --target install

# set the PATH for the install
before_test:
  - set PATH=%INSTALL_PREFIX%/bin;%PATH%

# execute the command line utility
test_script:
  - SoapySDRUtil --info
  - SoapySDRUtil --make="driver=null"
