########################################################################
## AppVeyor config for SoapySDR
########################################################################

version: '{build}'

platform: x64

configuration: Release

# Operating system (build VM template)
os: Windows Server 2012 R2

# branches to build
branches:
  # whitelist
  only:
    - master

# configure and build
build_script:
  - mkdir build
  - cd build
  - cmake ../ -G "Visual Studio 12 Win64" -DGPLOK=FALSE
  - cmake --build . --config Release
  - cmake --build . --config Release --target install
